FROM python:3.13

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Collect static (caso tenha)
RUN python rifas_ganns/manage.py collectstatic --noinput

CMD ["gunicorn", "rifas_ganns.rifas_ganns.wsgi:application", "--bind", "0.0.0.0:8000"]

