# Generated by Django 5.2.5 on 2025-09-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.CharField(choices=[('client', 'Cliente'), ('admin', 'Admin'), ('seller', 'Vendedor')], default='client', max_length=10, verbose_name='Escopo'),
        ),
    ]
