# Generated by Django 5.2.8 on 2025-12-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email de contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Telefone de contato'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
