# Generated by Django 5.2.8 on 2025-12-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_phone_unique_together_remove_phone_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
