# Generated by Django 5.2.8 on 2025-12-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_id',
            new_name='gateway_id',
        ),
    ]
