# Generated by Django 5.2.5 on 2025-08-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('LG', 'LIGHT'), ('DK', 'DARK')], default='LG', max_length=2)),
            ],
        ),
    ]
