# Generated by Django 5.2.5 on 2025-09-04 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_initial'),
        ('raffles', '0004_remove_raffle_can_set_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_winner_by_email', models.BooleanField(default=True)),
                ('can_set_percentage', models.BooleanField(default=False)),
                ('raffle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='raffles.raffle')),
            ],
        ),
    ]
