# Generated by Django 5.2.5 on 2025-09-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_raffleconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raffleconfiguration',
            old_name='can_set_percentage',
            new_name='use_manual_percentage',
        ),
    ]
