# Generated by Django 5.2.8 on 2025-12-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_rename_can_set_percentage_raffleconfiguration_use_manual_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffleconfiguration',
            name='use_manual_percentage',
        ),
    ]
