# Generated by Django 5.2.8 on 2025-12-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_raffleconfiguration_use_manual_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('test_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('production_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_endpoint', models.URLField()),
                ('payment_endpoint', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='raffleconfiguration',
            options={'verbose_name': 'Configuração da rifa', 'verbose_name_plural': 'Configurações das rifas'},
        ),
        migrations.AlterModelOptions(
            name='userconfiguration',
            options={'verbose_name': 'Configuração do usuário', 'verbose_name_plural': 'Configurações dos usuários'},
        ),
    ]
