# Generated by Django 5.2.8 on 2025-12-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_gatewayconfiguration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewayconfiguration',
            name='production_api_key',
        ),
        migrations.RemoveField(
            model_name='gatewayconfiguration',
            name='test_api_key',
        ),
        migrations.AlterField(
            model_name='gatewayconfiguration',
            name='name',
            field=models.CharField(choices=[('stripe', 'STRIPE'), ('pagarme', 'PAGARME')], max_length=255),
        ),
    ]
