# Generated by Django 5.2.8 on 2025-12-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_remove_gatewayconfiguration_production_api_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewayconfiguration',
            options={'verbose_name': 'Configuração do gateway', 'verbose_name_plural': 'Configuração dos gateways'},
        ),
    ]
