# Generated by Django 5.2.8 on 2025-12-08 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_alter_gatewayconfiguration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayRequiredCustomerFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_field_name', models.CharField(max_length=255)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.gatewayconfiguration')),
            ],
            options={
                'verbose_name': 'Campo obrigatório p/ cadastrar customer',
                'verbose_name_plural': 'Campos obrigatórios p/ cadastrar customer',
            },
        ),
    ]
