# Generated by Django 5.2.5 on 2025-08-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotas',
            },
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('prize_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quota_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quota_count', models.IntegerField()),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Raffle',
                'verbose_name_plural': 'Raffles',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='RafflePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raffle_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Raffle Picture',
                'verbose_name_plural': 'Raffle Pictures',
            },
        ),
    ]
