# Generated by Django 5.2.4 on 2025-08-04 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('prize_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quota_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raffle',
                'verbose_name_plural': 'Raffles',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='RafflePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raffle_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('main', models.BooleanField(default=False)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Raffle Picture',
                'verbose_name_plural': 'Raffle Pictures',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotas',
                'unique_together': {('raffle', 'number')},
            },
        ),
    ]
