# Generated by Django 5.2.5 on 2025-08-20 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raffles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quota',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='raffles.raffle'),
        ),
        migrations.AddField(
            model_name='rafflepicture',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='raffles.raffle'),
        ),
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together={('raffle', 'number')},
        ),
    ]
