# Generated by Django 5.2.5 on 2025-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='can_set_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raffle',
            name='manual_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual manualmente adicionado pelo administrador.', max_digits=5, null=True),
        ),
    ]
