# Generated by Django 5.2.5 on 2025-09-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_raffle_can_set_percentage_raffle_manual_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='can_set_percentage',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='manual_percentage',
        ),
    ]
