# Generated by Django 5.2.5 on 2025-09-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_remove_raffle_can_set_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
