# Generated by Django 5.2.8 on 2025-12-02 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0006_raffle_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RaffleSellerPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payment_links', to='raffles.raffle')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_payment_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raffle Seller Payment Link',
                'verbose_name_plural': 'Raffle Seller Payment Links',
            },
        ),
    ]
