# Generated by Django 5.2.8 on 2025-12-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0007_quota_seller_rafflesellerpaymentlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaffleSellerPaymentLink',
        ),
    ]
