# Generated by Django 5.2.8 on 2025-12-04 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0008_delete_rafflesellerpaymentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='prize_value',
        ),
        migrations.CreateModel(
            name='PreAwardedQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_number', models.IntegerField()),
                ('block_number', models.BooleanField(default=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='PrizePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raffle_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('main', models.BooleanField(default=False)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.prize')),
            ],
        ),
        migrations.CreateModel(
            name='RafflePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=True)),
                ('roulette', models.BooleanField(default=False)),
                ('awarded_quota', models.BooleanField(default=False)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.prize')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle')),
            ],
        ),
    ]
