# Generated by Django 5.2.8 on 2025-12-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0009_prize_remove_raffle_prize_value_preawardedquota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preawardedquota',
            name='block_number',
            field=models.BooleanField(default=True, verbose_name='Bloqueia o número impossibilitando de comprar'),
        ),
        migrations.AlterField(
            model_name='preawardedquota',
            name='quota_number',
            field=models.IntegerField(verbose_name='Número da cota'),
        ),
        migrations.AlterField(
            model_name='preawardedquota',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle', verbose_name='Rifa'),
        ),
    ]
