# Generated by Django 5.2.8 on 2025-12-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0010_alter_preawardedquota_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='minimum_selling_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='amount_to_sell',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor de venda total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raffle',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentagem de cotas vendidas'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='quota_count',
            field=models.IntegerField(verbose_name='Quantidade de cotas total'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='quota_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da cota'),
        ),
    ]
