# Generated by Django 5.2.8 on 2025-12-04 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0011_prize_minimum_selling_value_raffle_amount_to_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='prizes',
            field=models.ManyToManyField(through='raffles.RafflePrize', through_fields=['raffle', 'prize'], to='raffles.prize'),
        ),
        migrations.AlterField(
            model_name='raffleprize',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='raffles.prize'),
        ),
    ]
