# Generated by Django 5.2.8 on 2025-12-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0012_raffle_prizes_alter_raffleprize_prize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preawardedquota',
            options={'verbose_name': 'Cota pré-selecionada', 'verbose_name_plural': 'Cotas pré-selecionadas'},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'verbose_name': 'Prêmio', 'verbose_name_plural': 'Prêmios'},
        ),
        migrations.AlterModelOptions(
            name='prizepicture',
            options={'verbose_name': 'Foto do prêmio', 'verbose_name_plural': 'Fotos do prêmio'},
        ),
        migrations.AlterModelOptions(
            name='quota',
            options={'verbose_name': 'Cota', 'verbose_name_plural': 'Cotas'},
        ),
        migrations.AlterModelOptions(
            name='raffle',
            options={'ordering': ['-draw_date'], 'verbose_name': 'Rifa', 'verbose_name_plural': 'Rifas'},
        ),
        migrations.AlterModelOptions(
            name='rafflepicture',
            options={'verbose_name': 'Foto da rifa', 'verbose_name_plural': 'Fotos da rifa'},
        ),
        migrations.AlterModelOptions(
            name='raffleprize',
            options={'verbose_name': 'Prêmio x rifa', 'verbose_name_plural': 'Prêmios x rifas'},
        ),
    ]
